version: '3'
services:
  nginx:
    build:
      context: Nginx/
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - services

  redis:
    image: redis
    ports:
      - '6379:6379'
    container_name: redis
    networks:
      - queue

  app-api:
    build:
      context: Arretadas-API/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - queue
      - services
    depends_on:
      - redis
      #- app-bot

#  app-bot:
#   build:
#     context: Arretadas-bot/
#     dockerfile: Dockerfile
#    networks:
#      - queue
#    depends_on:
#      - redis

networks:
  queue:
    driver: bridge
  services:
    driver: bridge