version: '3'
services:
  nginx:
    build:
      context: Nginx/
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - services

  app-api:
    build:
      context: Arretadas-api/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - services
    depends_on:
      - app-bot

  app-bot:
    build:
      context: Arretadas-bot/
      dockerfile: Dockerfile
    volumes:
      - $pwd/tokens/:/usr/src/app/tokens

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ./application_default_credentials.json
    


networks:
  services:
    driver: bridge